apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  APP_NAME: "collector-v1"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  JWT_ALG: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
