apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=              # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=          # postgres
  POSTGRES_DB: cG9zdGdyZXM=                # postgres
